### ISSUE TITLE
EpiTreePrior.t was -Infinity

### ISSUE THREAD

**Issue by xieruopeng** [tgvaughan/EpiInf#6]
Hi Tim,

When I tried to implement EpiInf model based on my own sequences, I met such error:

"Start likelihood: -Infinity after 10 initialisation attempts
P(posterior) = -Infinity (was -Infinity)
	P(prior) = -Infinity (was -Infinity)
		P(EpiTreePrior.t:HK_BA_2_2_v1) = -Infinity (was -Infinity)
                 ..."
Fatal exception: Could not find a proper state to initialise. Perhaps try another seed.

I've tried to adjust parameters in "Epi Tree Prior" panel. It doesn't work. But the example sequences is working. I'm just wondering if any special requirements for the sequencing data using EpiInf. Or any suggestions for this?

Many thanks in advance!

Cheers,
Ruopeng

**Comment by tgvaughan** [comment]
Hi Ruopeng,

This isn't a bug, but rather is a very common problem with all BEAST analyses.  There's likely nothing wrong with your sequence data, but for some reason the starting configuration is evaluating to a probability of zero.

There are several reasons this might happen:
1. The initial tree height might be older than the start of the process (as indicated by the initial value of the "origin" parameter).  Fixing this would be as easy as increasing the start value of the origin, or reducing the TMRCA of the initial tree by reducing the popSize parameter used by RandomTree.
2. The sample times might fall in time intervals having a zero sampling rate.  This is an easy mistake to make, and fixing this just involves correcting the sampling rate shift times.
3. It might be the case that the probability of your starting configuration is actually non-zero, but estimation of this probability via EpiInf's monte carlo approach is resulting in an underflow.  This could be the case if your starting parameter values are too far into the tails of the posterior (i.e. are too incompatible with the data) and/or the number of particles you're using for the estimation is too low.  Try adjusting the starting values (origin, birth/death/sampling rates, etc) and changing the number of particles.
4. Finally, you might also want to try increasing the number of initialisation attempts from 10 to, say, 1000.  This can be done by adding the attribute `numInitializationAttempts="1000"` to the <run> element of the XML.

Good luck!
Tim
